#!/bin/bash
#
# build - compile and optionally install ninvaders
#

build_ninvaders() {
  [ -f cmake_build/ninvaders ] || {
    cmake -B cmake_build
    cmake --build cmake_build -j2
  }
}

usage() {
    printf "\nUsage: ./build [-i] [-p prefix] [-u]"
    printf "\nWhere:"
    printf "\n\t-i indicates install"
    printf "\n\t-p prefix specifies installation prefix (default /usr)"
    printf "\n\t-u displays this usage message and exits\n"
    exit 1
}

INSTALL=
platform=`uname -s`
if [ "${platform}" == "Darwin" ]
then
  PREFIX="/usr/local"
else
  PREFIX="/usr"
fi
while getopts "ip:u" flag; do
    case $flag in
        i)
            INSTALL=1
            ;;
        p)
            PREFIX="$OPTARG"
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

arch=
centos=
debian=
fedora=
darwin=

if [ "${platform}" == "Darwin" ]
then
  darwin=1
  brew install cmake
else
  [ -f /etc/os-release ] && . /etc/os-release
  [ "${ID_LIKE}" == "debian" ] && debian=1
  [ "${ID}" == "arch" ] && arch=1
  [ "${ID}" == "centos" ] && centos=1
  [ "${ID}" == "fedora" ] && fedora=1
  [ "${debian}" ] || [ -f /etc/debian_version ] && debian=1

  if [ "${debian}" ]
  then
    PKGS="build-essential libncurses-dev cmake"
    if [ "$1" == "-r" ]
    then
      sudo apt remove ${PKGS}
    else
      sudo apt install ${PKGS} pandoc zip
    fi
  else
    if [ "${arch}" ]
    then
      PKGS="base-devel cmake ncurses"
      if [ "$1" == "-r" ]
      then
        sudo pacman -Rs ${PKGS}
      else
        sudo pacman -S --needed ${PKGS} pandoc zip
      fi
    else
      have_dnf=`type -p dnf`
      if [ "${have_dnf}" ]
      then
        PINS=dnf
      else
        PINS=yum
      fi
      sudo ${PINS} makecache
      if [ "${fedora}" ]
      then
        PKGS="cmake ncurses-devel"
        if [ "$1" == "-r" ]
        then
          sudo ${PINS} -y remove ${PKGS}
          sudo ${PINS} -y groupremove "Development Tools" "Development Libraries"
        else
          sudo ${PINS} -y groupinstall "Development Tools" "Development Libraries"
          sudo ${PINS} -y install ${PKGS} pandoc zip
        fi
      else
        if [ "${centos}" ]
        then
          PKGS="cmake ncurses-devel"
          if [ "$1" == "-r" ]
          then
            sudo ${PINS} -y remove ${PKGS}
            sudo ${PINS} -y groupremove "Development Tools"
          else
            sudo ${PINS} -y groupinstall "Development Tools"
            sudo ${PINS} -y install ${PKGS} pandoc zip
          fi
        else
          echo "Unrecognized operating system"
        fi
      fi
    fi
  fi
fi

build_ninvaders
