#!/bin/bash
#
# build - compile and optionally install ninvaders
#

build_ninvaders() {
  [ -f cmake_build/ninvaders ] || {
    cmake -B cmake_build
    cmake --build cmake_build -j2
  }
}

usage() {
    printf "\nUsage: ./build [-i] [-p prefix] [-u]"
    printf "\nWhere:"
    printf "\n\t-i indicates install"
    printf "\n\t-p prefix specifies installation prefix (default /usr)"
    printf "\n\t-u displays this usage message and exits\n"
    exit 1
}

INSTALL=
PREFIX=/usr
while getopts "ip:u" flag; do
    case $flag in
        i)
            INSTALL=1
            ;;
        p)
            PREFIX="$OPTARG"
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

build_ninvaders
