#!/bin/bash

arch=
debian=
fedora=
darwin=

export __ASC_SRC__=`pwd`

platform=`uname -s`
if [ "${platform}" == "Darwin" ]
then
  darwin=1
else
  [ -f /etc/os-release ] && . /etc/os-release
  [ "${ID_LIKE}" == "debian" ] && debian=1
  [ "${ID}" == "arch" ] || [ "${ID_LIKE}" == "arch" ] && arch=1
  [ "${ID}" == "fedora" ] && fedora=1
  [ "${debian}" ] || [ -f /etc/debian_version ] && debian=1
fi

if [ "${debian}" ]
then
  sudo apt update
  pkg/mkdeb.sh
else
  if [ "${arch}" ]
  then
    sudo pacman -Syy
    pkg/mkaur.sh
  else
    if [ "${fedora}" ]
    then
      sudo dnf update
      pkg/mkrpm.sh fedora
    else
      if [ "${darwin}" ]
      then
        pkg/mkmac.sh
      else
        echo "Unsupported platform"
      fi
    fi
  fi
fi
